In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.metrics import confusion_matrix
import nltk
from nltk.corpus import stopwords


In [19]:
df = pd.read_csv('dataset_t.csv', header = 0)
df
                

Category                                        Description
0    Critical   I noticed a withdrawal from my account that I...
1    Critical  I tried withdrawing cash from an ATM, but it d...
2      Medium   I sent a wire transfer, but the recipient has...
3      Medium  My online banking is showing the wrong balance...
4    Critical  Hey, I believe someone has accessed my account...
..        ...                                                ...
196       Low                     Does a US transfer take long\n
197       Low  I am yet to receive the money in my account ho...
198       Low  I desperately need to transfer something from ...
199       Low  When does my transfer from the US arrive in my...
200       Low              How long does it take to get my money

[201 rows x 2 columns]

In [20]:
print(df.columns)

Index(['Category', 'Description'], dtype='object')


In [21]:
df.isnull().sum()

Category       3
Description    3
dtype: int64

In [22]:
df = df.dropna()

In [23]:
df.isnull().sum()

Category       0
Description    0
dtype: int64

In [24]:
df_shu = df.sample(frac=1, random_state=42) 
df_shu

Category                                        Description
66        Low  What are the current interest rates for saving...
115    Medium  I've received a notice of account delinquency ...
16   Critical  I got a scam call in the name of a bank and pe...
142    Medium  It’s been days  I am requesting for assistance...
159  Critical  I don't recognize this withdrawal on my statement
..        ...                                                ...
107    Medium  I've been waiting for a response regarding a s...
14     Medium  Hi, I've been trying to dispute a transaction,...
93        Low                 How to open Demat account online ?
182       Low  What is needed for my daughter to open an acco...
103    Medium  I've been charged for services I never signed ...

[198 rows x 2 columns]

In [8]:
df.groupby('Category').Category.count()

Category
Critical    66
Low         74
Medium      58
Name: Category, dtype: int64

In [25]:
def text_process(mess):
    """
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. Returns a list of the cleaned text
    """
    # Check characters to see if they are in punctuation
    nopunc = [char for char in mess if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    # Now just remove any stopwords
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [10]:
df_shu

Category                                        Description
66        Low  What are the current interest rates for saving...
115    Medium  I've received a notice of account delinquency ...
16   Critical  I got a scam call in the name of a bank and pe...
142    Medium  It’s been days  I am requesting for assistance...
159  Critical  I don't recognize this withdrawal on my statement
..        ...                                                ...
107    Medium  I've been waiting for a response regarding a s...
14     Medium  Hi, I've been trying to dispute a transaction,...
93        Low                 How to open Demat account online ?
182       Low  What is needed for my daughter to open an acco...
103    Medium  I've been charged for services I never signed ...

[198 rows x 2 columns]

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
import string


In [27]:
bow_transformer = CountVectorizer(analyzer=text_process).fit(df['Description'])
bow_transformer

CountVectorizer(analyzer=<function text_process at 0x2a98ec0e0>)

In [153]:
bow_transformer.vocabulary_

{'noticed': 320,
 'withdrawal': 498,
 'account': 54,
 'didnt': 174,
 'make': 297,
 'help': 243,
 'look': 289,
 'tried': 464,
 'withdrawing': 500,
 'cash': 117,
 'ATM': 5,
 'doublecharged': 185,
 'Could': 14,
 'fix': 214,
 'sent': 414,
 'wire': 496,
 'transfer': 462,
 'recipient': 375,
 'hasnt': 240,
 'received': 371,
 'yet': 509,
 'check': 126,
 'online': 326,
 'banking': 97,
 'showing': 420,
 'wrong': 508,
 'balance': 95,
 'causing': 118,
 'concern': 139,
 'assist': 84,
 'Hey': 26,
 'believe': 99,
 'someone': 426,
 'accessed': 51,
 'without': 503,
 'permission': 345,
 'Hello': 24,
 'found': 218,
 'suspicious': 443,
 'charges': 125,
 'credit': 150,
 'card': 116,
 'statement': 432,
 'investigate': 266,
 'Hi': 27,
 'cant': 115,
 'log': 284,
 'seems': 412,
 'updates': 477,
 'back': 94,
 'urgently': 480,
 'need': 314,
 'loan': 281,
 'application': 76,
 'stuck': 440,
 'expedite': 206,
 'think': 453,
 'theres': 452,
 'error': 197,
 'interest': 263,
 'rate': 366,
 'savings': 401,
 'take': 445

In [28]:
messages_bow = bow_transformer.transform(df['Description'])
messages_bow

<198x509 sparse matrix of type '<class 'numpy.int64'>'
	with 1344 stored elements in Compressed Sparse Row format>

In [29]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer().fit(messages_bow)
tfidf4 = tfidf_transformer.transform(messages_bow)
print(tfidf4)

  (0, 497)	0.3512765946178318
  (0, 320)	0.46844211881399683
  (0, 297)	0.33621214781314085
  (0, 289)	0.46844211881399683
  (0, 242)	0.3512765946178318
  (0, 174)	0.40593614148084206
  (0, 53)	0.19107776294489606
  (1, 499)	0.4348437090119929
  (1, 463)	0.40335996110921285
  (1, 213)	0.3636951296864349
  (1, 185)	0.4348437090119929
  (1, 116)	0.31805439067256785
  (1, 13)	0.3810218864781278
  (1, 4)	0.2837467506074359
  (2, 508)	0.33282630795853835
  (2, 495)	0.3699489106966002
  (2, 461)	0.26450565202490534
  (2, 413)	0.3875736031320424
  (2, 375)	0.44232089830554655
  (2, 371)	0.3152016155230961
  (2, 239)	0.3555484884396303
  (2, 125)	0.33282630795853835
  (3, 507)	0.3840960323837508
  (3, 419)	0.34029213072110653
  (3, 326)	0.3206205046874057
  :	:
  (193, 287)	0.4835494794671938
  (193, 43)	0.6132425929408494
  (194, 508)	0.4213483696564977
  (194, 444)	0.40957112708512683
  (194, 370)	0.5599653179737722
  (194, 309)	0.35849316624605354
  (194, 287)	0.40957112708512683
  (194, 53

In [30]:
from sklearn.model_selection import train_test_split

text_train, text_test, label_train, label_test = train_test_split(df['Description'], df['Category'], test_size=0.1, random_state = 3)



In [32]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
pipeline = Pipeline([
    ('bow', CountVectorizer()),  # strings to token integer counts
    ('tfidf', TfidfTransformer()),  # integer counts to weighted TF-IDF scores
    ('classifier', SVC()),  # train on TF-IDF vectors w/ SVM
])


In [33]:
from sklearn.naive_bayes import MultinomialNB
pipeline = Pipeline([
    ('bow', CountVectorizer()),        # strings to token integer counts
    ('tfidf', TfidfTransformer()),    # integer counts to weighted TF-IDF scores
    ('classifier', MultinomialNB()),  # train on TF-IDF vectors with Multinomial Naive Bayes
])

In [34]:
pipeline.fit(text_train,label_train)

Pipeline(steps=[('bow', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('classifier', MultinomialNB())])

In [35]:
predictions = pipeline.predict(text_test.iloc[1:2].values
)
predictions

array(['Critical'], dtype='<U8')

In [36]:
predictions = pipeline.predict(text_test)
predictions

array(['Critical', 'Critical', 'Low', 'Low', 'Low', 'Medium', 'Medium',
       'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low',
       'Critical', 'Critical', 'Critical', 'Critical'], dtype='<U8')

In [37]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(label_test,predictions)
print(cm)

[[ 4  1  0]
 [ 0 10  0]
 [ 2  1  2]]


In [38]:
# confusion matrix and classification report(precision, recall, F1-score)
# ytest = np.array(label_test)
print(classification_report(pipeline.predict(text_test),label_test))

              precision    recall  f1-score   support

    Critical       0.80      0.67      0.73         6
         Low       1.00      0.83      0.91        12
      Medium       0.40      1.00      0.57         2

    accuracy                           0.80        20
   macro avg       0.73      0.83      0.74        20
weighted avg       0.88      0.80      0.82        20



In [39]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(predictions,label_test))

Accuracy: 0.8


In [40]:
# file = open('/content/news.txt','r')
# news = file.read()
# file.close()

news = input("Enter news = ")
news_data = {'predict_news':[news]}
news_data_df = pd.DataFrame(news_data)

predict_news_cat = pipeline.predict(news_data_df['predict_news'])
print("Predicted ticket category = ",predict_news_cat[0])


Enter news =  I lost my ATM card and there is transaction I don't know


Predicted ticket category =  Critical


In [41]:
import pickle

# Save the trained pipeline to a file
with open('final_model_ticket.pkl', 'wb') as file:
    pickle.dump(pipeline, file)

In [110]:
I can't log 

SyntaxError: unterminated string literal (detected at line 1) (172679240.py, line 1)